import Navbar from '@/components/landing/Navbar';

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen pt-24 pb-16 bg-gray-50/30 dark:bg-gray-950">
        <div className="max-w-3xl mx-auto px-6">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-8">Terms of Service</h1>
          
          <div className="prose prose-gray dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed text-gray-600 dark:text-gray-300">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 1 (Purpose)</h2>
              <p>These Terms of Service govern the rights, obligations, and responsibilities between AgentMarket (hereinafter &ldquo;the Company&rdquo;) and its users in connection with the use of the AI agent marketplace service (hereinafter &ldquo;the Service&rdquo;) provided by the Company.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 2 (Definitions)</h2>
              <p>① &ldquo;Service&rdquo; refers to the AI agent-based conversational service and related ancillary services provided by the Company.</p>
              <p>② &ldquo;User&rdquo; refers to any person who uses the Service in accordance with these Terms.</p>
              <p>③ &ldquo;AI Agent&rdquo; refers to an automated conversational system that performs specific functions based on artificial intelligence technology.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 3 (Effectiveness of Terms)</h2>
              <p>① These Terms become effective upon posting on the Service interface or by otherwise notifying users.</p>
              <p>② The Company may amend these Terms to the extent permitted by applicable law, and any amended Terms shall be notified in the same manner as described in Paragraph 1.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 4 (Use of Service)</h2>
              <p>① Users may use the Service in accordance with the procedures established by the Company.</p>
              <p>② The Service is available 24 hours a day, 365 days a year in principle; however, it may be temporarily suspended due to system maintenance or other reasons.</p>
              <p>③ Responses from AI Agents are for reference purposes only and do not constitute professional advice in areas such as law, medicine, or finance.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 5 (User Obligations)</h2>
              <p>Users shall not engage in any of the following activities:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Unauthorized collection or use of personal information of others</li>
                <li>Creation of content for illegal purposes using the Service</li>
                <li>Interference with the normal operation of the Service</li>
                <li>Commercial use of information obtained through the Service without prior consent of the Company</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 6 (Limitation of Liability)</h2>
              <p>① The Company does not guarantee the accuracy, completeness, or timeliness of responses generated by AI Agents.</p>
              <p>② Users bear full responsibility for any decisions or actions taken based on AI responses.</p>
              <p>③ The Company shall not be liable for the use of free services except as specifically required by applicable law.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 7 (Paid Services)</h2>
              <p>① Fees and payment methods for paid services are separately specified within the Service.</p>
              <p>② Payment cancellations and refunds are subject to applicable laws and Company policies.</p>
              <p>③ Subscription cancellations take effect from the next billing date.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Article 8 (Dispute Resolution)</h2>
              <p>Disputes arising from these Terms shall be governed by the laws of the Republic of Korea, and the competent court shall be the court having jurisdiction over the Company&rsquo;s principal place of business.</p>
            </section>

            <p className="text-gray-400 dark:text-gray-500 mt-8">Effective Date: February 3, 2026</p>
          </div>
        </div>
      </main>
    </>
  );
}
